apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-todo-app-service
spec:
  selector:
    app: todo-app
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 6969
  type: {{ .Values.service.type }}