apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-flask-todo-app-service
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 5000 # Match this with your containerPort in deployment.yaml
  selector:
    app: flask-todo-app